embed_assets: on
package_assets: on
javascripts:
  vendor:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.easing.js
    - public/javascripts/vendor/date.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/polymaps.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/maptip.js
    - public/javascripts/vendor/d3/d3.js
    - public/javascripts/vendor/d3/d3.geo.js
    - public/javascripts/vendor/d3/d3.geom.js
    - public/javascripts/vendor/d3/d3.behavior.js
    - public/javascripts/vendor/d3/d3.layout.js
    - public/javascripts/vendor/d3/d3.time.js
  app:
    - public/javascripts/lib/*.js
    - public/javascripts/*.js
    - public/javascripts/application.js
stylesheets:
  core:
    - public/stylesheets/reset.css
    - public/stylesheets/core.css
    - public/stylesheets/data.css
    - public/stylesheets/pictos.css
    - public/stylesheets/maptip.css
    - public/stylesheets/vendor/tipsy.css
